### ISSUE TITLE
CF7 Integration

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#134] opened 2018-11-14 22:25 UTC
Contact Form 7 version 5.0.5
ConvertKit 1.6.2

Steps to recreate:

1. Add several contact forms in CF7
2. Go to Settings > ConvertKit > CF7 tab
3. Change ConvertKit form to any form
4. Press Save Changes. 
5. Changes are not saved.

ref: https://secure.helpscout.net/conversation/698150273/291176?folderId=956509

**Comment by dylanfeltus** [comment] 2018-12-04 04:44
@growdev Duplicate of #107?

**Comment by tnorthcutt** [comment] 2019-01-07 21:18
Fixed by https://github.com/ConvertKit/ConvertKit-WordPress/pull/137

**Closed** 2019-01-07 21:19 UTC
Labels: bug
